use_frameworks!

platform :ios, '13.0'

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end

target 'SMPopupService_Example' do
  pod 'SMPopupService', :path => '../'

  pod 'SnapKit','~> 4.2.0'

  target 'SMPopupService_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
