use_frameworks!

platform :ios, '10.0'

target 'SMPopupService_Example' do
  pod 'SMPopupService', :path => '../'

  target 'SMPopupService_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
